export const actionIds = {
	PUBLIC_GAMES_REQUEST_START: 'PUBLIC_GAMES_REQUEST_START',
	PUBLIC_GAMES_REQUEST_COMPLETED: 'PUBLIC_GAMES_REQUEST_COMPLETED',

	PLAYERS_ADD: 'PLAYERS_ADD',
	PLAYERS_REMOVE: 'PLAYERS_REMOVE',
	PLAYERS_CLEAR: 'PLAYERS_CLEAR',

	GAME_CONNECT_REQUEST_START: 'GAME_CONNECT_REQUEST_START',
	GAME_CONNECT_REQUEST_COMPLETED: 'GAME_CONNECT_REQUEST_COMPLETED',
	GAME_CONNECT_REQUEST_FAILED: 'GAME_CONNECT_REQUEST_FAILED',
	GAME_DISCONNECT_REQUEST_START: 'GAME_DISCONNECT_REQUEST_START',
	GAME_DISCONNECT_REQUEST_COMPLETED: 'GAME_DISCONNECT_REQUEST_COMPLETED',
	GAME_UPDATE_INFO: 'GAME_UPDATE_INFO',
}

export interface BaseAction {
	type: string
	payload?: any
}
